### ISSUE TITLE
how to checkout password length before model save?

### ISSUE THREAD

**Issue by icepoint0** [codahale/bcrypt-ruby#144]
validates hook doesn'work on the password that bcrypt generrates.

**Comment by tjschuck** [comment]
You can't get any information about the password from the hash — that's by design.

If you want to use a validation to check the length, you need to do it on the plaintext password before hashing it.

You're probably looking for something along these lines, assuming:

1. You're using Rails
2. You have a `User` model
3. Your `User` model has a `password_digest` attribute

```ruby
class User < ActiveRecord::Base
  attr_reader :password

  validates :password, length: { minimum: 8 }

  def password=(unencrypted_password)
    @password = unencrypted_password
    if unencrypted_password.present?
      self.password_digest = BCrypt::Password.create(unencrypted_password)
    end
  end
end
```
