### ISSUE TITLE
Rails Console: LoadError: cannot load such file -- BCrypt

### ISSUE THREAD

**Issue by mellogarrett** [codahale/bcrypt-ruby#145]
First, I added `gem 'bcrypt'` to my gemfile, then ran `bundle install`. When I launch the rails console and try to run `require 'bcrypt'` I get the error `LoadError: cannot load such file -- BCrypt
`

**Comment by tjschuck** [comment]
But `bundle install` succeeded?  What OS and version?

Are you getting to the console with `bundle exec rails console`, i.e. in the context of Rails knowing about your bundled gems?

**Comment by mellogarrett** [comment]
Yes, `bundle install` succeeded. I'm on Mac OS Sierra. Bcrypt version 3.1.11

Just tried `bundle exec rails console` and still get the error

**Comment by tjschuck** [comment]
So you actually shouldn't have to `require 'bcrypt'` if you're going through Rails, because it should autoload it (unless you put `require: false` in your Gemfile... did you?)

But that said, it still shouldn't error out — it should just return `false` if it has already been required:

```
$ bundle exec rails console
> require 'bcrypt'
=> false
```

But I assume if you type just `BCrypt` in your console, you get `NameError: uninitialized constant BCrypt`, right?

Are you using `spring`?  Try `spring stop` first, then `bundle exec rails console` and see if it was just a preloading cache issue.

**Comment by mellogarrett** [comment]
Nice. Running `spring stop` fixed it. Thanks @tjschuck!

**Comment by tjschuck** [comment]
Phew!  Glad we sorted it out :heart: :heart: :heart_eyes_cat: :heart:
