### ISSUE TITLE
Hash Comparisons Ruby 2.4.0

### ISSUE THREAD

**Issue by daBee** [codahale/bcrypt-ruby#147]
I can't seem to get the methods to compare to `true`:

		require 'bcrypt'

		pw = "alphasprouts34"
		hashed = BCrypt::Password.create(pw)	
		puts hashed		# $2a$10$0Cs9TbGEkmx67ysZl7pVjOfvmNOwQRiS2RaiYZB0CuuvSFm/N3HVC
		returned = BCrypt::Password.new(hashed)
		puts returned		# $2a$10$0Cs9TbGEkmx67ysZl7pVjOfvmNOwQRiS2RaiYZB0CuuvSFm/N3HVC

		puts BCrypt::Password.create(pw) == BCrypt::Password.new(hashed)			# => false
		puts pw == returned			# => false

Brought it down to basic gem management instead of going to PG.  I can't seem to make this work.  I expect them to be equal.  The documentation is identical, from what I can see.  Yes I am not using a hash, as that is one layer of confusion on top of all this.

**Comment by daBee** [comment]
Looking at methods for the BCrypt::Password object that I stored in the database, I have the following methods that would be helpful:

		==
		===
		eql?
		equal?
		inspect
		!=

Then the interesting part.  The vast amount of methods return false, but one true:

		require 'bcrypt'

		@res = conn.exec_params(
			%q{ SELECT password FROM users WHERE username = $1 },
			['peter']	)
		r = @res.getvalue(0,0)
		puts "r:" + r

		held = BCrypt::Password.new(r)		# Password
		puts "held: " + held
		puts held == pw				# => true
		puts pw == held				# => false
		puts held.eql?(pw)				# => false
		puts pw.eql?(held)				# => false
		puts held.equal?(pw)			# => false
		puts pw.equal?(held)			# => false
		puts held != pw				# => false
		puts held === pw				# => false
		puts
		puts held.inspect           # => "$2a$10$mmTIpDHa9VZDrYZpRj9.x.R1/ihCEcjqwQZQbHsFwnn/tzDHtd9x6"

`held == pw` and `pw == held` give different results.

**Comment by aubreywahl** [comment]
I am having the exact same problem!

**Comment by tjschuck** [comment]
You're misunderstanding how bcrypt's hashing works and how you can check for password matches.

Note that `==` in Ruby is just a method, and it's not necessarily commutative like you're trying to make it be:

```ruby
puts held == pw    # => true
puts pw == held    # => false
```

There's no guarantee that `a == b` will be the same as `b == a` in Ruby.

For a trivial example, consider this:

```ruby
class Foo
  def ==(other)
    true
  end
end

class Bar
  def ==(other)
    false
  end
end

foo = Foo.new
bar = Bar.new

puts foo == bar  # true
puts bar == foo  # false
```

Specifically, in your example, `held` is an instance of `BCrypt::Password`, and `pw` is an instance of `String`.

So for `pw == held`, you're calling the method [`String#==`](http://ruby-doc.org/core-2.4.0/String.html#method-i-3D-3D), effectively asking `"alphasprouts34" == "$2a$10$mmTIpDHa9VZDrYZpRj9.x.R1/ihCEcjqwQZQbHsFwnn/tzDHtd9x6"`, which obviously returns false, since those two _strings_ are not equal.

However, when calling `held == pw`, you're calling the method [`BCrypt::Password#==`](https://github.com/codahale/bcrypt-ruby/blob/23b0517e20e7ddf2e733c1bcdb22b0b12166f042/lib/bcrypt/password.rb#L64-L68), which is specifically implemented to handle this case as a convenience method.

Instead of thinking in terms of "equality", think in terms of `is_password?`, which is an alias for `BCrypt::Password#==`.  So instead of `held == pw`, think `held.is_password?(pw)`.  That's the same thing, and then you shouldn't see anything logically wrong with:

```ruby
puts held.is_password?(pw)    # => true
puts pw == held               # => false
```

See my comment on https://github.com/codahale/bcrypt-ruby/issues/99 for effectively the same explanation in different words.
