### ISSUE TITLE
Slow execution speed in BCrypt::Engine.hash_secret method

### ISSUE THREAD

**Issue by dmitriystrukov** [codahale/bcrypt-ruby#161]
So, i collided with that problem in my pet project. I have admin panel and devise authentication, when I tried to login it's took a long of time. I started debugging and finally found method which cause that issue.

https://github.com/codahale/bcrypt-ruby/blob/master/lib/bcrypt/engine.rb#L45
https://github.com/codahale/bcrypt-ruby/blob/master/ext/mri/bcrypt_ext.c#L29

```
Benchmark.measure do 
  BCrypt::Engine.hash_secret('example', '$2a$20$UqqVd9iimPFFj9lDyHnqJe')
end
```

![2017-10-24 15 21 22](https://user-images.githubusercontent.com/29231078/31942749-13e3ed68-b8cf-11e7-828d-961d633e20d7.png)

![2017-10-24 15 23 43](https://user-images.githubusercontent.com/29231078/31942838-5a406fb6-b8cf-11e7-8366-d55757642716.png)

**Comment by tjschuck** [comment]
Yes, that's precisely the purpose of bcrypt — it's intentionally slow in order to mitigate brute force attacks.

That said, this speed-vs-security balance is configurable via bcrypt's "cost" parameter.  In your example:

```ruby
BCrypt::Engine.hash_secret('example', '$2a$20$UqqVd9iimPFFj9lDyHnqJe')
```

you're generating a bcrypt hash using a cost of _20_ (the second attribute among the `$` delimiters), and that's a _very_ high cost factor.  I don't know your particular needs, but a cost in the 10-14 range is much more typical today.  Quickly checking on my machine, costs of 10, 12, and 14 all come in at:

```ruby
> Benchmark.ms { BCrypt::Password.create("asdf", cost: 10) }
=> 66.74899999052286
> Benchmark.ms { BCrypt::Password.create("asdf", cost: 12) }
=> 236.3130000012461
> Benchmark.ms { BCrypt::Password.create("asdf", cost: 14) }
=> 894.4489999994403
```

Whether you want something that takes 66 milliseconds or almost a full second is up to your particular app and security needs.  Note that this cost factor will _exponentially_ increase the time it takes to compute a hash, so the fact that a cost of 20 takes you more than a minute isn't surprising at all:

```ruby
> Benchmark.ms { BCrypt::Password.create("asdf", cost: 20) }
=> 59210.6189999904
```

You can learn more about bcrypt and it's cost parameter [via Wikipedia](https://en.wikipedia.org/wiki/Bcrypt).  If you want to learn a little more about the history and context of why bcrypt is intentionally slow, you can check out [this video](https://www.youtube.com/watch?v=9u54O6vARK8).  (Yes, that's me speaking.  I'm not trying to self-promote; it's just an explanation that should do a sufficient job explaining the behavior you're seeing.)

**Comment by dmitriystrukov** [comment]
@tjschuck Thank you!
