### ISSUE TITLE
hash emails

### ISSUE THREAD

**Issue by dowi** [codahale/bcrypt-ruby#163]
Hi and thanks a lot

I have a regulatory need to hash emails.
Using this gem, i can hash the email and save it into the DB, but each time the algorithm creates a different hash (probably because of salt?) and so later I cannot search the DB by email.

Does this algorithm can be used for that? 

Thanks a lot

**Comment by tjschuck** [comment]
Though I suppose you _could_ use bcrypt for that, you probably shouldn't.

In particular, if you're trying to look up records in your database _by_ email and don't have some other attribute to query upon, you won't be able to look up the record in your database by email alone; you'll have to loop through every record comparing the email to the hash (because of the individual salting).  If you only have, say, a dozen records, I suppose that's feasible, but if you're looking at more than that, the computational complexity of looking up a single record would probably be excessive.

**Comment by dowi** [comment]
Got it - Thanks!
