### ISSUE TITLE
AWS ElasticBean is unable to download this gem

### ISSUE THREAD

**Issue by RailsCod3rFuture** [codahale/bcrypt-ruby#177]
For some reason, ElasticBean is failing when I upload the app to AWS Server. Do you have an idea to why the gem might not be downloading from your repository? I'll post a picture in this thread soon.

**Comment by tjschuck** [comment]
Can't think of any specific bcrypt-ruby reasons that you wouldn't be able to download this from AWS.

Without any more details, my two random guesses are:

1. Something blocking rubygems.org altogether in your config, but that should cause all gems to fail.
2. Something blocking it because it contains C code and/or compiled binaries?  But that seems unlikely as well...

Anyway, closing this pending more info (like actual error messages), but will gladly reopen once you can provide some more info!

Thanks!
