### ISSUE TITLE
How to do a dummy password check similar by time with actual password check?

### ISSUE THREAD

**Issue by sanavy** [codahale/bcrypt-ruby#179]
From the README:

```ruby
def login
  @user = User.find_by_email(params[:email])
  if @user.password == params[:password]
    give_token
  else
    redirect_to home_url
  end
end
```

Maybe there should be timeout similar by time with any password check before redirect to secure unauthorised checks of emails in the database?
How to do this?

Thanks

**Comment by waiting-for-dev** [comment]
@shhavel I think your question was relevant. Did you find a way?

**Comment by shhavel** [comment]
@waiting-for-dev 

Define in library method for dummy password check:

```ruby
module BCrypt
  class Password
    def self.dummy_checkpw
      # Compare "dummy_password" with "dummy_password2"
      new('$2a$10$EC9EjM7aFmhgI0D/PHwi2eHqNU4oBDP0dnef7Op/bNQCSfRhn.8I6') == 'dummy_password2'
    end
  end
end
```

or maybe (if this takes same time):

```ruby
module BCrypt
  class Password
    def self.dummy_checkpw
      BCrypt::Engine.hash_secret('password', BCrypt::Engine.generate_salt(BCrypt::Engine.cost))
      false
    end
  end
end
```

Then use dummy password check in authentication:

```ruby
def login
  @user = User.find_by_email(params[:email])

  if @user
    if @user.password == params[:password]
      give_token
    else
      redirect_to home_url
    end
  else
    # Perform dummy check if user with given email doesn't exist.
    BCrypt::Password.dummy_checkpw
    redirect_to home_url
  end
end

```

**Comment by waiting-for-dev** [comment]
Thanks @shhavel !

Can I ask the maintainers whether they think it would be a good idea to integrate in the library? It would be easy to prepare a PR by @shhavel (if he wants) or myself.

**Comment by tjschuck** [comment]
Ooof, I'm torn on that, but leaning towards no.  This is very much not actually a thing that would be a part of this library in a pure sense, but I get the appeal.  Since it's kind of just a one-liner whether or not it's in bcrypt-ruby natively, I'm more inclined towards no.  At best, maybe included in the README as a sort of user-enumeration timing-attack style recommendation, but even that feels more "generalized security best practice tips and tricks" style thing than bcrypt-ruby specific (i.e., that problem is the same for bcrypt and any other password hashing scheme with non-trivial execution time).

That said, thanks for putting the info in this issue!  At least hopefully it'll have enough searchability to help someone looking for this information in the future.
