### ISSUE TITLE
Thoughts on a pure ruby bcrypt?

### ISSUE THREAD

**Issue by copiousfreetime** [codahale/bcrypt-ruby#224]
I may have need of a pure ruby bcrypt implementation.

I just added bcrypt2 support to [htauth](https://github.com/copiousfreetime/htauth) and it looks like this may cause some issues downstream in folks using htauth in their chef cookbooks since there is now a C extension dependency. (https://github.com/redguide/htpasswd/pull/34) 

Any thoughts - (1) on whether this is even a good idea or not, and (2) if I go down this path would this be something that bcrypt-ruby would want to have be part of its gem, or should I look at a completely second gem - say in the manner of [json_pure](https://rubygems.org/gems/json_pure)?

**Comment by tjschuck** [comment]
It's probably not a good idea.  The reason for using a C implementation is performance, which seems ironic considering bcrypt is an intentionally slow algorithm, but a fast implementation allows you to use higher cost factors and increase the security of your stored hashes.  Since an attacker will be using the fastest implementation available to them, decreasing your cost for the sake of tolerable performance for your end users is worse for their overall security.

What's probably a better solution for your library's users is to use some combination of `bundle package` and `bundle install --local` to use a precompiled .gem package in your `vendor/cache`.

**Comment by copiousfreetime** [comment]
I'm assuming on the performance side that that's not really an issue as the use is to manage the entries of an htpasswd file. I'm not sure if the chef cookbooks use bundler under the covers or not - I'll forward that information on, thanks for the feedback.

**Comment by copiousfreetime** [comment]
All understandable and I basically agree with you :-).  Thanks.

And just to be clear - The main use of the htauth gem is to manage the entries in the htpasswd file, not to do the actual authentication. In fact, I didn't even provide an api for checking a password as valid until recently. Folks use my gem to programmatically add/update/remove entries in the htpasswd / htdigest files for administration and leave the actual authentication to apache/nginx/etc.

**Comment by tjschuck** [comment]
Gotcha, that makes sense.

The best approach for people without access to a compiler at install time would still probably be to precompile and vendor a version for themselves.
